---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0 

- name: Wait for SECONDARY to be {{ crm_mon_demoted }}
  include_tasks: wait/wait_secondary_be_demoted.yaml

- name: Wait for SECONDARY to be {{ crm_mon_sok }}
  include_tasks: wait/wait_secondary_be_sok.yaml

- name: Wait for counter of SECONDARY be bigger than PRIMARY
  include_tasks: wait/wait_prim_counter_bigger_than_sec.yaml