---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0 

- name: Gather AWS info for instances
  include_tasks: hana/get_aws_info.yaml

- name: Reboot primary node
  include_tasks: hana/reboot_primary.yaml
  when: GLOBAL_HANA_PRIMARY_NODE_PRIVATE_IP != ""

- name: Wait for failover to happen
  include_tasks: "{{ role_path }}/tasks/shared/hana/wait_failover_sec_to_prim.yaml"

- name: Wait for HANA to be fully up after instance reboot
  include_tasks: "{{ role_path }}/tasks/shared/hana/wait/wait_hana_be_fully_up.yaml"

- name: Wait for new SECONDARY instance to be up
  include_tasks: "{{ role_path }}/tasks/shared/hana/wait_primary_restablish_reboot.yaml"